version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/f1z9f8i1/betterkanban-ui-dev
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t betterkanban-ui-dev .
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker tag betterkanban-ui-dev:latest public.ecr.aws/f1z9f8i1/betterkanban-ui-dev:latest
      - docker push public.ecr.aws/f1z9f8i1/betterkanban-ui-dev:latest
